---
name: CraftOS-PC action
author: Commandcracker
description: Run CraftOS-PC as an GitHub action

branding:
    icon: terminal
    color: white

inputs:
    root:
        description: The root directory of the craftos-pc containg a startup.lua
        required: false
        default: "./"
    timeout:
        description:
            Specifies the maximum amount of time that the action will run before timing out.
            "timeout is a floating point number with an optional suffix:"
            's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days.
            A duration of 0 disables the associated timeout.
        required: false
        default: "60"
    disable_root:
        description:
            This will disable mounting the root directory making the root input useless.
            Use this if root files are mounted with user data directory.
        required: false
    directory:
        description: Sets the directory that stores user data
        required: false
    luajit:
        description: Setting this will use CraftOS-PC Accelerated (with LuaJIT) instead of default CraftOS-PC (with PUC Lua)
        required: false
    options:
        description: These are the options that will be passed to CraftOS-PC
        required: false
    disable_tweaks:
        description: Setting this will dsiable all CraftOS-PC-Tweaks
        required: false
    disable_default_settings:
        description: Setting this will dsiable all default CraftOS-PC settings.
            This is required if you want to delete .settings for some odd reason.
        required: false
    id:
        description: Sets the ID of the computer that will launch
        required: false
    timeout_signal:
        description: specify the signal to be sent on timeout;
            SIGNAL may be a name like 'HUP' or a number;
            see 'kill -l' for a list of signals
        required: false
        default: "HUP"
    disable_timeout_verbose:
        description: This will disable verbose timeout, not printing if a timeout accoured.
        required: false
    timeout_arguments:
        description: Defines additional timeout arguments.
        required: false
    disable_single:
        description: Setting this will disable the single window render mode.
            It is not recommended to do this unless you know what you are doing.
        required: false
    disable_headless:
        description: Setting this will disable the headless render mode.
            It is not recommended to do this unless you know what you are doing.
        required: false

runs:
    using: docker
    image: docker://ghcr.io/commandcracker/craftos-pc-action-image:234f5d4ebc237af45b57869b7c6cb9cc23509ece
    env:
        TIMEOUT: ${{inputs.timeout}}
        OPTIONS: ${{inputs.options}}
        LUAJIT: ${{inputs.luajit}}
        ROOT: ${{inputs.root}}
        DIRECTORY: ${{inputs.directory}}
        ID: ${{inputs.id}}
        DISABLE_TWEAKS: ${{inputs.disable_tweaks}}
        DISABLE_DEFAULT_SETTINGS: ${{inputs.disable_default_settings}}
        DISABLE_ROOT: ${{inputs.disable_root}}
        DISABLE_HEADLESS: ${{inputs.disable_headless}}
        DISABLE_SINGLE: ${{inputs.disable_single}}
        DISABLE_TIMEOUT_VERBOSE: ${{inputs.disable_timeout_verbose}}
        TIMEOUT_SIGNAL: ${{inputs.timeout_signal}}
        TIMEOUT_ARGUMENTS: ${{inputs.timeout_arguments}}
